=== ValaskaGergo/XMLGYAK/AQBMIV_1207 BEADANDO/DOMParseAQBMIVbeadando/XMLSchemaAQBMIV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/XMLSchemaFOQH34" elementFormDefault="qualified">
<xs:element name="adatbazis">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ugyfel" type="UgyfelTipus" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="uzlet" type="UzletTipus" maxOccurs="unbounded"/>
				<xs:element name="fodrasz" type="FodraszTipus" maxOccurs="unbounded"/>
				<xs:element name="tulajdonos" type="TulajdonosTipus" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		
		<xs:key name="UgyfelKulcs">
		<xs:selector xpath="ugyfel"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="UzletKulcs">
		<xs:selector xpath="uzlet"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="FodraszKulcs">
		<xs:selector xpath="fodrasz"/>
		<xs:field xpath="@id" />
		</xs:key>
		<xs:key name="TulajdonosKulcs">
		<xs:selector xpath="tulajdonos"/>
		<xs:field xpath="@id" />
		</xs:key>
	</xs:element>
	
<xs:simpleType name="nev">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:simpleType name="kor">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<xs:simpleType name="nem">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:simpleType name="UgyID">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<xs:complexType name="UgyfelTipus">
		<xs:sequence>
			<xs:element name="nev" type="nev"/>
			<xs:element name="kor" type="kor"/>
			<xs:element name="nem" type="nem"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType> 

<xs:simpleType name="ferohely">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	
	<xs:simpleType name="nyitvatartas">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	
	
	<xs:complexType name="UzletTipus">
		<xs:sequence>
			<xs:element name="ferohely" type="ferohely"/>
			<xs:element name="nyitvatartas" type="nyitvatartas"/>
			<xs:element name="cim" type="cimTipus"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType> 

<xs:simpleType name="varos">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:simpleType name="utca">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	<xs:complexType name="cimTipus">
		<xs:sequence>
			<xs:element name="varos" type="varos"/>
			<xs:element name="utca" type="utca"/>
		</xs:sequence>
	</xs:complexType> 

	
	<xs:simpleType name="kereset">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	
	
	<xs:complexType name="FodraszTipus">
		<xs:sequence>
			<xs:element name="nev" type="nev"/>
			<xs:element name="kor" type="kor"/>
			<xs:element name="kereset" type="kereset"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType> 

	
	<xs:simpleType name="profit">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	

	
	<xs:complexType name="TulajdonosTipus">
		<xs:sequence>
			<xs:element name="nev" type="nev"/>
			<xs:element name="kor" type="kor"/>
			<xs:element name="profit" type="profit"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType> 

</xs:schema>

=== ValaskaGergo/XMLGYAK/XML TASK AQBMIV/DOMPARSE AQBMIV/XMLAQBMIV.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<adatbazis xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaAQBMIV.xsd">

  <ugyfel id="Ugy0">
    <nev>Tóth Ferenc</nev>
    <kor>17</kor>
    <nem>Ferfi</nem>
   </ugyfel>
   
  <ugyfel id="Ugy1">
    <nev>Kiss Greta</nev>
    <kor>29</kor>
    <nem>Nő</nem>
    </ugyfel>
        		
  <ugyfel id="Ugy2">
    <nev>Hasas Csaba</nev>
    <kor>23</kor>
    <nem>Ferfi</nem>
  </ugyfel>
  
  
  <uzlet id="Uzi0">
  <ferohely>145</ferohely>
  <nyitvatartas>8-16</nyitvatartas>
     <cim>
     <varos>Miskolc</varos>
     <utca>Hősök tere</utca>
     </cim>
  </uzlet>
       
       
  <fodrasz id="F0">
  <nev>Gál József</nev>
  <kor>22</kor>
  <kereset>250000</kereset>
  </fodrasz>
  
 <fodrasz id="F1">
  <nev>Szabó Dániel</nev>
   <kor>24</kor>
  <kereset>450000</kereset>
  </fodrasz>
        		
  <fodrasz id="F2">
   <nev>Cziko Tivadar</nev>
   <kor>33</kor>
   <kereset>298000</kereset>
  </fodrasz>
        		
        		
  <tulajdonos id="T0">
  <nev>Kemény Tamás</nev>
  <kor>24</kor>
   <profit>1230000</profit>
  </tulajdonos>
        
</adatbazis>
